
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
//import net.sourceforge.tess4j.TesseractException;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.FontUIResource;
import net.sourceforge.tess4j.TesseractException;
import net.sourceforge.tess4j.ITesseract;
//import net.sourceforge.tess4j.Tesseract1;
import net.sourceforge.tess4j.Tesseract;
import say.swing.JFontChooser;

public class SwingP extends javax.swing.JFrame {

    /**
     * Creates new form SwingP
     */
    static SwingP mainwindow;
    File openFile;
    JFileChooser chooser;
    JFileChooser chooser1;
    public RED a;
    public int id;
    public int readwriteid;
    public String User;
    public static LightIde shareable;

    public SwingP() {
        this.chooser = new JFileChooser();
        this.chooser1 = new JFileChooser();
        id = 0;
        readwriteid = 0;
        initComponents();
        //jScrollPane1.add( Box.createVerticalStrut(jScrollPane1.getHeight()) );
//         jScrollPane1.add(canvas1);   
//        jButton3.
//        jButton3.setOpaque(true);
//        jButton3.setBorderPainted(false);
    }

    public SwingP(String usr) {
        this.chooser = new JFileChooser();
        this.chooser1 = new JFileChooser();
        id = 0;
        readwriteid = 0;
        User = usr;
        initComponents();
        //jScrollPane1.add( Box.createVerticalStrut(jScrollPane1.getHeight()) );
//         jScrollPane1.add(canvas1);   
//        jButton3.
//        jButton3.setOpaque(true);
//        jButton3.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Eraser = new javax.swing.JButton();
        LineButt = new javax.swing.JButton();
        ClearButt = new javax.swing.JButton();
        Rect = new javax.swing.JButton();
        ovalButt = new javax.swing.JButton();
        strokeSize = new javax.swing.JSlider();
        checkFill = new javax.swing.JCheckBox();
        networkLabel = new javax.swing.JLabel();
        ConnectButt = new javax.swing.JButton();
        readRelate = new javax.swing.JButton();
        WriteButt = new javax.swing.JButton();
        readwriteRelate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DisconnectButt = new javax.swing.JButton();
        strokeLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        colorLabel = new javax.swing.JLabel();
        ocrControls = new javax.swing.JLabel();
        ConvertTButt = new javax.swing.JButton();
        EditINTB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textButt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        canvas1 = new Canvas();
        jMenuBar2 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openmenu = new javax.swing.JMenuItem();
        savemenuitem = new javax.swing.JMenuItem();
        exitmenuitem = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        Aboutus = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paintect");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Eraser.setText("Eraser");
        Eraser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraserActionPerformed(evt);
            }
        });

        LineButt.setText("Line");
        LineButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineButtActionPerformed(evt);
            }
        });

        ClearButt.setText("Clear");
        ClearButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtActionPerformed(evt);
            }
        });

        Rect.setText("Rectangle");
        Rect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RectActionPerformed(evt);
            }
        });

        ovalButt.setText("Oval");
        ovalButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovalButtActionPerformed(evt);
            }
        });

        strokeSize.setValue(0);
        strokeSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                strokeSizeStateChanged(evt);
            }
        });

        checkFill.setText("Fill Shapes");
        checkFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFillActionPerformed(evt);
            }
        });

        networkLabel.setText("Networking Controls");

        ConnectButt.setText("Connect");
        ConnectButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectButtActionPerformed(evt);
            }
        });

        readRelate.setText("Read");
        readRelate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readRelateActionPerformed(evt);
            }
        });

        WriteButt.setText("Write");
        WriteButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteButtActionPerformed(evt);
            }
        });

        readwriteRelate.setText("Read/Write");
        readwriteRelate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readwriteRelateActionPerformed(evt);
            }
        });

        jLabel4.setText("Connection Relationship");

        DisconnectButt.setText("Disconnect");
        DisconnectButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisconnectButtActionPerformed(evt);
            }
        });

        strokeLabel.setText("Stroke Size");

        jLabel8.setText("More Stuff");

        jButton9.setText("PaintectoCode");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel9.setText("Light Weight IDE which Supports");

        jLabel11.setText("Code formatting and running for C,C++");

        jLabel12.setText("Java,Python and also works as Text Editor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(networkLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(LineButt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClearButt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(Rect, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ovalButt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(strokeSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(strokeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(checkFill, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(DisconnectButt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(ConnectButt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(readwriteRelate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(readRelate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                            .addComponent(WriteButt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Eraser, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rect, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ovalButt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(strokeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strokeSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClearButt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LineButt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(Eraser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkFill, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConnectButt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisconnectButt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readRelate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WriteButt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(readwriteRelate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Eraser.getAccessibleContext().setAccessibleName("");
        LineButt.getAccessibleContext().setAccessibleName("");
        ClearButt.getAccessibleContext().setAccessibleName("");
        Rect.getAccessibleContext().setAccessibleName("");
        ovalButt.getAccessibleContext().setAccessibleName("");

        jButton3.setBackground(Color.red);
        jButton3.setBorder(null);
        jButton3.setDoubleBuffered(true);
        jButton3.setFocusPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(Color.green);
        jButton2.setBorder(null
        );
        jButton2.setDoubleBuffered(true);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(Color.BLUE);
        jButton4.setBorder(null
        );
        jButton4.setDoubleBuffered(true);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(Color.BLACK);
        jButton5.setBorder(null
        );
        jButton5.setDoubleBuffered(true);
        jButton5.setFocusPainted(false);
        jButton5.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(Color.MAGENTA);
        jButton6.setBorder(null);
        jButton6.setDoubleBuffered(true);
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(Color.GRAY);
        jButton7.setBorder(null
        );
        jButton7.setDoubleBuffered(true);
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(Color.DARK_GRAY);
        jButton8.setBorder(null);
        jButton8.setDoubleBuffered(true);
        jButton8.setFocusPainted(false);
        jButton8.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton15.setBackground(Color.ORANGE);
        jButton15.setBorder(null);
        jButton15.setDoubleBuffered(true);
        jButton15.setFocusPainted(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(Color.YELLOW);
        jButton16.setBorder(null);
        jButton16.setDoubleBuffered(true);
        jButton16.setFocusPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(Color.WHITE);
        jButton17.setBorder(null);
        jButton17.setDoubleBuffered(true);
        jButton17.setFocusPainted(false);
        jButton17.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(Color.CYAN);
        jButton18.setBorder(null);
        jButton18.setDoubleBuffered(true);
        jButton18.setFocusPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(Color.pink);
        jButton19.setBorder(null);
        jButton19.setDoubleBuffered(true);
        jButton19.setFocusPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton1.setText("More Colors");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        colorLabel.setText("Color Swatches");

        ocrControls.setText("OCR Controls");

        ConvertTButt.setText("Convert To Text");
        ConvertTButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertTButtActionPerformed(evt);
            }
        });

        EditINTB.setText("Edit in TextBox");
        EditINTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditINTBActionPerformed(evt);
            }
        });

        jLabel1.setText("More Collab Options");

        textButt.setText("Code/Text Collab");
        textButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textButtActionPerformed(evt);
            }
        });

        jLabel2.setText("These features provide real time ");

        jLabel3.setText("designing graphics while also");

        jLabel5.setText("letting you work on related text/code");

        jLabel6.setText("whilist collaborating with peers.");

        jLabel7.setText("in inbuilt IDE provided ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ocrControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ConvertTButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EditINTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocrControls, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConvertTButt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditINTB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textButt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setMaximumSize(new java.awt.Dimension(5000, 5000));
        jPanel5.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel5.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        canvas1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout canvas1Layout = new javax.swing.GroupLayout(canvas1);
        canvas1.setLayout(canvas1Layout);
        canvas1Layout.setHorizontalGroup(
            canvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2460, Short.MAX_VALUE)
        );
        canvas1Layout.setVerticalGroup(
            canvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2040, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3000;
        gridBagConstraints.ipady = 3000;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(canvas1, gridBagConstraints);

        jScrollPane3.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jScrollPane3.getAccessibleContext().setAccessibleDescription("");

        jScrollPane1.setViewportView(jPanel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1127;
        gridBagConstraints.ipady = 717;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 3);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jMenuBar2.setPreferredSize(new java.awt.Dimension(64, 30));

        fileMenu.setText("File");

        openmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openmenu.setText("Open");
        openmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openmenuActionPerformed(evt);
            }
        });
        fileMenu.add(openmenu);

        savemenuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        savemenuitem.setText("Save");
        savemenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savemenuitemActionPerformed(evt);
            }
        });
        fileMenu.add(savemenuitem);

        exitmenuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitmenuitem.setText("Exit");
        exitmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitmenuitemActionPerformed(evt);
            }
        });
        fileMenu.add(exitmenuitem);

        jMenuBar2.add(fileMenu);

        settingsMenu.setText("Settings");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Configure SQL Settings");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        settingsMenu.add(jMenuItem1);

        jMenuBar2.add(settingsMenu);

        help.setText("Help");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Help");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        help.add(jMenuItem3);

        jMenuBar2.add(help);

        aboutMenu.setText("About");

        Aboutus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_MASK));
        Aboutus.setText("About Us");
        Aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutusActionPerformed(evt);
            }
        });
        aboutMenu.add(Aboutus);

        jMenuBar2.add(aboutMenu);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        canvas1.red();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        canvas1.green();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        canvas1.blue();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        More a = new More();
//        a.setVisible(true);
//        a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        canvas1.g2.setColor(JColorChooser.showDialog(null, null, canvas1.g2.getColor()));


    }//GEN-LAST:event_jButton1ActionPerformed

    private void savemenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savemenuitemActionPerformed
        // TODO add your handling code here:
        BufferedImage a = (BufferedImage) canvas1.image;
        FileNameExtensionFilter pngFilter = new FileNameExtensionFilter("png files (*.png)", "png");
        // add filters
        chooser1.addChoosableFileFilter(pngFilter);
        chooser1.setFileFilter(pngFilter);
        int returnVal = chooser1.showSaveDialog(Rect);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // System.out.println("You chose to open this file: " );

//            BufferedImage img = null;
            File aa = chooser1.getSelectedFile();
            File s = new File(aa.getAbsolutePath() + ".png");
            try {

                ImageIO.write(a, "png", s);

            } catch (IOException ex) {
                Logger.getLogger(SwingP.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_savemenuitemActionPerformed

    private void ConvertTButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertTButtActionPerformed
        // TODO add your handling code here:
        Image z = canvas1.image;

        BufferedImage a = (BufferedImage) z;

        try {
            ImageIO.write(a, "TIF", new File("OCROUT$.TIF"));
        } catch (IOException ie) {
        }
        ITesseract tess = new Tesseract();

        tess.setDatapath("src");

        String Tex;
        try {
            Tex = tess.doOCR(new File("OCROUT$.TIF"));
            JOptionPane.showMessageDialog(null, Tex);

//       Tex=tess.doOCR(a);
//       new OCRout(Tex).setVisible(true);
        } catch (TesseractException e) {
            //JOptionPane.showMessageDialog(rootPane, e);
            JOptionPane.showMessageDialog(null, e.getMessage());

        }


    }//GEN-LAST:event_ConvertTButtActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        canvas1.black();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        canvas1.magenta(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        canvas1.gray();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        canvas1.dark_gray();// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        canvas1.orange();// TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        canvas1.yellow(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        canvas1.white();// TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        canvas1.cyan();// TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        canvas1.pink();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void AboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutusActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "The program is a mini-version of what a full fledged networking Paint would look like. Though there might be various limitations at the time being, we are constantly making updates to making it more sophisticated.\n It is being developed by three students of School Of Engineering and Applied Science as a part of their project.\nMany java utlities such as Java Swing,Java awt,Tesseract OCR(tess4j) along with SQL class is being put into use whilst developing the same.");
    }//GEN-LAST:event_AboutusActionPerformed

    private void openmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openmenuActionPerformed
        // TODO add your handling code here:
//        new JFileChooser().setVisible(true);
//        File a=new File()

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG , GIF , PNG,TIFF,TIF Images", "jpg", "gif", "tiff", "png", "tif");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(Rect);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // System.out.println("You chose to open this file: " );
            File a = chooser.getSelectedFile();
            BufferedImage img = null;
            try {
                img = ImageIO.read(a);
            } catch (IOException ex) {
                Logger.getLogger(SwingP.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

//            canvas1.setSize(img.getWidth(),img.getHeight());
//            canvas1.g2=(Graphics2D)img.getGraphics();
            canvas1.g2.drawImage(img, 0, 0, null);
            repaint();

        }

    }//GEN-LAST:event_openmenuActionPerformed

    private void exitmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenuitemActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_exitmenuitemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new SQLSettings().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void DisconnectButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnectButtActionPerformed
        // TODO add your handling code here:
        a.dispose();
        readwriteid = 0;
        canvas1.disconnect();
    }//GEN-LAST:event_DisconnectButtActionPerformed

    private void readwriteRelateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readwriteRelateActionPerformed
        // TODO add your handling code here:
        if (readwriteid == 0 || readwriteid == 3) {
            canvas1.write();
            readwriteid = 3;
        } else {
            JOptionPane.showMessageDialog(null, "Other Type Of Connection Relationship Already Defined Disconnect and Connect Again");
        }

        if (SwingP.canvas1.conn != null) {
            if (readwriteid == 0 || readwriteid == 3) {
                a = new RED(canvas1.connstring);
                readwriteid = 3;
            } else {
                JOptionPane.showMessageDialog(null, "Other Type Of Connection Relationship Already Defined Disconnect and Connect Again");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please Connect To Database");
        }
    }//GEN-LAST:event_readwriteRelateActionPerformed

    private void WriteButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteButtActionPerformed
        // TODO add your handling code here:
        if (readwriteid == 0 || readwriteid == 1) {
            canvas1.write();
            readwriteid = 1;
        } else {
            JOptionPane.showMessageDialog(null, "Other Type Of Connection Relationship Already Defined Disconnect and Connect Again");
        }
    }//GEN-LAST:event_WriteButtActionPerformed

    private void readRelateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readRelateActionPerformed
        // TODO add your handling code here:
        if (SwingP.canvas1.conn != null) {
            if (readwriteid == 0 || readwriteid == 2) {
                a = new RED(canvas1.connstring);
                readwriteid = 2;
            } else {
                JOptionPane.showMessageDialog(null, "Other Type Of Connection Relationship Already Defined Disconnect and Connect Again");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please Connect To Database");
        }
    }//GEN-LAST:event_readRelateActionPerformed

    private void ConnectButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectButtActionPerformed
        // TODO add your handling code here:
        canvas1.connectmysql();
    }//GEN-LAST:event_ConnectButtActionPerformed

    private void checkFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFillActionPerformed
        // TODO add your handling code here:
        if (canvas1.fill == 0) {
            canvas1.fill = 1;
        } else {
            canvas1.fill = 0;
        }
    }//GEN-LAST:event_checkFillActionPerformed

    private void strokeSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_strokeSizeStateChanged
        // TODO add your handling code here:
        canvas1.stroke(strokeSize.getValue());
    }//GEN-LAST:event_strokeSizeStateChanged

    private void ovalButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovalButtActionPerformed
        // TODO add your handling code here:
        canvas1.oval();
    }//GEN-LAST:event_ovalButtActionPerformed

    private void RectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RectActionPerformed
        // TODO add your handling code here:
        canvas1.rect();
    }//GEN-LAST:event_RectActionPerformed

    private void ClearButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtActionPerformed
        try {
            // TODO add your handling code here:
            canvas1.clear();
        } catch (InterruptedException ex) {
            Logger.getLogger(SwingP.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (a != null) {
            a.dispose();
            a = new RED(canvas1.connstring);
        }
    }//GEN-LAST:event_ClearButtActionPerformed

    private void LineButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineButtActionPerformed
        // TODO add your handling code here:
        canvas1.line();
    }//GEN-LAST:event_LineButtActionPerformed

    private void EraserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EraserActionPerformed
        // TODO add your handling code here:
        canvas1.erase();
    }//GEN-LAST:event_EraserActionPerformed

    private void EditINTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditINTBActionPerformed
        // TODO add your handling code here:
        Image z = canvas1.image;

        BufferedImage a = (BufferedImage) z;

        try {
            ImageIO.write(a, "TIF", new File("OCROUT$.TIF"));
        } catch (IOException ie) {
        }
        ITesseract tess = new Tesseract();

        tess.setDatapath("src");

        String Tex;
        try {
            Tex = tess.doOCR(new File("OCROUT$.TIF"));
            new OCRTB(Tex).setVisible(true);

//       Tex=tess.doOCR(a);
//       new OCRout(Tex).setVisible(true);
        } catch (TesseractException e) {
            //JOptionPane.showMessageDialog(rootPane, e);
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_EditINTBActionPerformed

    private void textButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textButtActionPerformed
        // TODO add your handling code 

        if (readwriteid == 1) {
            shareable = new LightIde();
            shareable.setVisible(true);
            REA b = new REA(canvas1.connstring);
            b.dispose();
            WRI a = new WRI(canvas1.connstring);
        }
        if (readwriteid == 2) {
            shareable = new LightIde();
            shareable.setVisible(true);
            REA b = new REA(canvas1.connstring);
        }
        if (readwriteid == 3) {
            JOptionPane.showMessageDialog(null, "Text Sharing is not possible in read write mode as of now!");
        }

    }//GEN-LAST:event_textButtActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        new LightIde().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "HELP\n"
                + "Shape controls\n"
                + "The application provides shapes(fill and outline) such as rectangle and oval to draw accurate figures.\n"
                + "Stroke slider helps to manage the width of the pen.\n"
                + "It is reflected in both line and shape.\n"
                + "\n"
                + "Various features such as open image,save image and exit are implemented in the file menu,whereas the Edit menu hold the Undo/Redo functionality.\n"
                + "\n"
                + "How to connect to server:\n"
                + "Write the ip address of your server in the SQLsettings menu.\n"
                + "Select connect to the SQL server by clicking on the connect button on the page. \n"
                + "Select the relationship you want between the classes(read/write) and begin to draw.\n"
                + "\n"
                + "\n"
                + "OCR Controls\n"
                + "Any text either drawn or from an image will be displayed on the screen on one \"Convert to Text\" button click.\n"
                + "Edit in textBox\n"
                + "Shows the converted text in a text editor.Any errors made by the system can be corrected manually from here.\n"
                + "\n"
                + "\n"
                + "Paintectocode: Is an online IDE which serves as a platform for compiling various programming languages(c,c++,python,java).\n"
                + "The code can be made to run in terminal by clicking shift+f6.");
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    public static void setUIFont(FontUIResource f) {
        Enumeration keys = UIManager.getDefaults().keys();
        while (keys.hasMoreElements()) {
            Object key = keys.nextElement();
            Object value = UIManager.get(key);
            if (value instanceof FontUIResource) {
                FontUIResource orig = (FontUIResource) value;
                Font font = new Font(f.getFontName(), orig.getStyle(), f.getSize());
                UIManager.put(key, new FontUIResource(font));
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                mainwindow = new SwingP();
                mainwindow.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Aboutus;
    private javax.swing.JButton ClearButt;
    private javax.swing.JButton ConnectButt;
    private javax.swing.JButton ConvertTButt;
    private javax.swing.JButton DisconnectButt;
    private javax.swing.JButton EditINTB;
    private javax.swing.JButton Eraser;
    private javax.swing.JButton LineButt;
    private javax.swing.JButton Rect;
    private javax.swing.JButton WriteButt;
    private javax.swing.JMenu aboutMenu;
    public static Canvas canvas1;
    private javax.swing.JCheckBox checkFill;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JMenuItem exitmenuitem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu help;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel networkLabel;
    private javax.swing.JLabel ocrControls;
    private javax.swing.JMenuItem openmenu;
    private javax.swing.JButton ovalButt;
    private javax.swing.JButton readRelate;
    private javax.swing.JButton readwriteRelate;
    private javax.swing.JMenuItem savemenuitem;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JLabel strokeLabel;
    private javax.swing.JSlider strokeSize;
    private javax.swing.JButton textButt;
    // End of variables declaration//GEN-END:variables
}
